 class AutomaticGradingSystem extends javax.swing.JFrame {

    /**
     * Creates new form AutomaticGradingSystem
     */
    public AutomaticGradingSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mathematics = new javax.swing.JLabel();
        english = new javax.swing.JLabel();
        science = new javax.swing.JLabel();
        filipino = new javax.swing.JLabel();
        ap = new javax.swing.JLabel();      
        pe = new javax.swing.JLabel();
        tle = new javax.swing.JLabel();
        history = new javax.swing.JLabel();
        mathTF = new javax.swing.JTextField();
        englishTF = new javax.swing.JTextField();
        scienceTF = new javax.swing.JTextField();
        filipinoTF = new javax.swing.JTextField();
        apTF = new javax.swing.JTextField();
        historyTF = new javax.swing.JTextField();
        tleTF = new javax.swing.JTextField();
        peTF = new javax.swing.JTextField();
        mletterTF = new javax.swing.JTextField();
        eletterTF = new javax.swing.JTextField();
        sletterTF = new javax.swing.JTextField();
        fletterTF = new javax.swing.JTextField();
        apletterTF = new javax.swing.JTextField();
        hletterTF = new javax.swing.JTextField();
        peletterTF = new javax.swing.JTextField();
        tleletterTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        averageTF = new javax.swing.JTextField();
        gpaTF = new javax.swing.JTextField();
        average = new javax.swing.JLabel();
        gpa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automatic Grading System\n");
        setBackground(new java.awt.Color(242, 200, 96));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Automatic Grading System");

        mathematics.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mathematics.setText("MATHEMATICS:");

        english.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        english.setText("ENGLISH:");

        science.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        science.setText("SCIENCE:");

        filipino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        filipino.setText("FILIPINO:");

        ap.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ap.setText("ARALIN PANLIPUNAN:");

        pe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pe.setText("PE AND HEALTH:");

        tle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tle.setText("TLE:");

        history.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        history.setText("HISTORY:");

        mathTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathTFActionPerformed(evt);
            }
        });

        englishTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishTFActionPerformed(evt);
            }
        });

        scienceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scienceTFActionPerformed(evt);
            }
        });

        filipinoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filipinoTFActionPerformed(evt);
            }
        });

        apTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apTFActionPerformed(evt);
            }
        });

        historyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyTFActionPerformed(evt);
            }
        });

        peTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peTFActionPerformed(evt);
            }
        });

        mletterTF.setEditable(false);
        mletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mletterTFActionPerformed(evt);
            }
        });

        eletterTF.setEditable(false);
        eletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletterTFActionPerformed(evt);
            }
        });

        sletterTF.setEditable(false);
        sletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sletterTFActionPerformed(evt);
            }
        });

        fletterTF.setEditable(false);
        fletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fletterTFActionPerformed(evt);
            }
        });

        apletterTF.setEditable(false);
        apletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apletterTFActionPerformed(evt);
            }
        });

        hletterTF.setEditable(false);
        hletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hletterTFActionPerformed(evt);
            }
        });

        peletterTF.setEditable(false);
        peletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peletterTFActionPerformed(evt);
            }
        });

        tleletterTF.setEditable(false);
        tleletterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tleletterTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Letter Grade");

        averageTF.setEditable(false);
        averageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                averageTFActionPerformed(evt);
            }
        });

        gpaTF.setEditable(false);
        gpaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpaTFActionPerformed(evt);
            }
        });

        average.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        average.setText("AVERAGE");

        gpa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gpa.setText("GPA");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mathematics)
                                    .addComponent(english)
                                    .addComponent(science)
                                    .addComponent(filipino))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(englishTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scienceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filipinoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(eletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(average, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(gpa))
                                                    .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(6, 6, 6))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ap)
                                    .addComponent(history)
                                    .addComponent(pe)
                                    .addComponent(tle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(apTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(apletterTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tleletterTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(peTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(peletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(historyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnClear))
                                .addGap(227, 227, 227))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(47, 47, 47)))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mathTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mathematics))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(englishTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(english))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scienceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(science)
                    .addComponent(sletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(average))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filipino)
                    .addComponent(filipinoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(averageTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(apletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(historyTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(peletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(peTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tleletterTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(btnClear)
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(gpa)
                        .addGap(12, 12, 12)
                        .addComponent(gpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(btnExit)
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>                        

    private void mathTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void apTFActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void peTFActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void mletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void eletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void sletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void fletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void apletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void hletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void peletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tleletterTFActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void averageTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void gpaTFActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Calculates all the grades 
        
        String mathematicsScore,englishScore, scienceScore, filipinoScore, apScore, historyScore, tleScore, peScore;
        double average;
        double gpa = 0;

        mathematicsScore = mathTF.getText ();    
        englishScore = englishTF.getText ();
        scienceScore = scienceTF.getText ();
        filipinoScore = filipinoTF.getText ();
        apScore = apTF.getText ();
        historyScore = historyTF.getText ();
        tleScore = tleTF.getText ();
        peScore = peTF.getText ();

        double mathematics = Double.parseDouble(mathematicsScore);
        double english = Double.parseDouble(englishScore);
        double science = Double.parseDouble(scienceScore);
        double filipino = Double.parseDouble(filipinoScore);
        double ap = Double.parseDouble(apScore);
        double history = Double.parseDouble(historyScore);
        double tle = Double.parseDouble(tleScore);
        double pe = Double.parseDouble(peScore);

        average = ((mathematics + english + science + filipino + ap + history + tle + pe) / 8);
        
        if (mathematics >= 94) {
            mletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (mathematics >= 84 && mathematics < 94){
            mletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (mathematics >= 74 && mathematics < 84){
            mletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (mathematics >= 64 && mathematics < 74){
            mletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (mathematics >= 57 && mathematics < 64){
            mletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (mathematics >= 50 && mathematics < 57){
            mletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            mletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (english >= 94) {
            eletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (english >= 84 && english < 94){
            eletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (english >= 74 && english < 84){
            eletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (english >= 64 && english < 74){
            eletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (english >= 57 && english < 64){
            eletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (english >= 50 && english < 57){
            eletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            eletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (science >= 94) {
            sletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (science >= 84 && science < 94){
            sletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (science >= 74 && science < 84){
            sletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (science >= 64 && science < 74){
            sletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (science >= 57 && science < 64){
            sletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (science >= 50 && science < 57){
            sletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            sletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (filipino >= 94) {
            fletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (filipino >= 84 && filipino < 94){
            fletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (filipino >= 74 && filipino < 84){
            fletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (filipino >= 64 && filipino < 74){
            fletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (filipino>= 57 && filipino < 64){
            fletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (filipino >= 50 && filipino < 57){
            fletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            fletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (ap >= 94) {
            apletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (ap >= 84 && ap < 94){
            apletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (ap >= 74 && ap < 84){
            apletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (ap >= 64 && ap < 74){
            apletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (ap >= 57 && ap < 64){
            apletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (ap >= 50 && ap < 57){
            apletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            apletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (history >= 94) {
            hletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (history >= 84 && history < 94){
            hletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (history >= 74 && history < 84){
            hletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (history >= 64 && history < 74){
            hletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (history >= 57 && history < 64){
            hletterTF.setText("B");
            gpa = gpa + 2.75;
        }else if (history >= 50 && history < 57){
            hletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            hletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        if (pe >= 94) {
            peletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (pe >= 84 && pe < 94){
            peletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (pe >= 74 && pe < 84){
            peletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (pe >= 64 && pe < 74){
            peletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (pe >= 57 && pe < 64){
            peletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (pe >= 50 && pe < 57){
            peletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            peletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        
        if (tle >= 94) {
            tleletterTF.setText("A+");
            gpa = gpa + 1.0;
        }else if (tle >= 84 && tle < 94){
            tleletterTF.setText("A");
            gpa = gpa + 1.50;
        }else if (tle >= 74 && tle < 84){
            tleletterTF.setText("B+");
            gpa = gpa + 2.00;
        }else if (tle >= 64 && tle < 74){
            tleletterTF.setText("B");
            gpa = gpa + 2.50;
        }else if (tle >= 57 && tle < 64){
            tleletterTF.setText("C");
            gpa = gpa + 2.75;
        }else if (tle >= 50 && tle < 57){
            tleletterTF.setText("D");
            gpa = gpa + 3.0;
        }else {
            tleletterTF.setText("F");
            gpa = gpa + 5.0;
        }
        
        
        gpa = gpa / 8;
        
        gpaTF.setText(Double.toString(gpa));
        averageTF.setText(Double.toString(average));
    }                                        

    private void scienceTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void englishTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void filipinoTFActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void historyTFActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Clears all fields 
        
        mathTF.setText(" ");
        englishTF.setText(" ");
        scienceTF.setText(" ");
        filipinoTF.setText(" ");
        apTF.setText(" ");
        historyTF.setText(" ");
        peTF.setText(" ");
        tleTF.setText(" ");
        mletterTF.setText(" ");
        eletterTF.setText(" ");
        sletterTF.setText(" ");
        fletterTF.setText(" ");
        apletterTF.setText(" ");
        hletterTF.setText(" ");
        peletterTF.setText(" ");
        tleletterTF.setText(" ");
        
        averageTF.setText(" ");
        gpaTF.setText(" ");
    
    }                                        

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // exit jframe
          System.exit(0);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomaticGradingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomaticGradingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomaticGradingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomaticGradingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomaticGradingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel ap;
    private javax.swing.JTextField apTF;
    private javax.swing.JTextField apletterTF;
    private javax.swing.JLabel average;
    private javax.swing.JTextField averageTF;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JTextField eletterTF;
    private javax.swing.JLabel english;
    private javax.swing.JTextField englishTF;
    private javax.swing.JLabel filipino;
    private javax.swing.JTextField filipinoTF;
    private javax.swing.JTextField fletterTF;
    private javax.swing.JLabel gpa;
    private javax.swing.JTextField gpaTF;
    private javax.swing.JLabel history;
    private javax.swing.JTextField historyTF;
    private javax.swing.JTextField hletterTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField mathTF;
    private javax.swing.JLabel mathematics;
    private javax.swing.JTextField mletterTF;
    private javax.swing.JLabel pe;
    private javax.swing.JTextField peTF;
    private javax.swing.JTextField peletterTF;
    private javax.swing.JLabel science;
    private javax.swing.JTextField scienceTF;
    private javax.swing.JTextField sletterTF;
    private javax.swing.JLabel tle;
    private javax.swing.JTextField tleTF;
    private javax.swing.JTextField tleletterTF;
    // End of variables declaration                   
}
